### ISSUE TITLE
fn test_bound_check_gadget() -> min vs max difference

### ISSUE THREAD

**Issue by hansieodendaal** [lovesh/bulletproofs-r1cs-gadgets#2]
Hi @lovesh,

Function fails with large difference between min and max:

**Test 1**
_Used:_
```
let min = std::u64::MAX/100001;
let max = std::u64::MAX/100000; 
```

_Result: (Passed)_
```
Testing started at 10:53 ...
v is 184466284608320
```

**Test 2**
_Used:_
```
let min = std::u64::MAX/100009; 
let max = std::u64::MAX/100000; 
```

_Result: (Failed)_
```
Testing started at 10:50 ...
v is 184453846428645

thread 'gadget_bound_check::tests::test_bound_check_gadget' panicked at 'called `Result::unwrap()` on an `Err` value: VerificationError', src\libcore\result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libstd\sys_common\backtrace.rs:76
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libstd\sys_common\backtrace.rs:60
   3: core::fmt::write
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libcore\fmt\mod.rs:1028
   4: std::io::Write::write_fmt<test::Sink>
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\src\libstd\io\mod.rs:1412
   5: std::io::impls::{{impl}}::write_fmt<Write>
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libstd\io\impls.rs:141
   6: std::sys_common::backtrace::_print
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libstd\sys_common\backtrace.rs:64
   7: std::sys_common::backtrace::print
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libstd\sys_common\backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libstd\panicking.rs:196
   9: std::panicking::default_hook
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libstd\panicking.rs:207
  10: std::panicking::rust_panic_with_hook
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libstd\panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libstd\panicking.rs:380
  12: std::panicking::rust_begin_panic
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libstd\panicking.rs:307
  13: core::panicking::panic_fmt
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libcore\panicking.rs:84
  14: core::result::unwrap_failed
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libcore\result.rs:1165
  15: core::result::Result<(), bulletproofs::errors::R1CSError>::unwrap<(),bulletproofs::errors::R1CSError>
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\src\libcore\result.rs:933
  16: bulletproofs_examples::gadget_bound_check::tests::test_bound_check_gadget
             at .\src\gadget_bound_check.rs:144
  17: bulletproofs_examples::gadget_bound_check::tests::test_bound_check_gadget::{{closure}}
             at .\src\gadget_bound_check.rs:123
  18: core::ops::function::FnOnce::call_once<closure-0,()>
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\src\libcore\ops\function.rs:227
  19: alloc::boxed::{{impl}}::call_once<(),FnOnce<()>>
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\src\liballoc\boxed.rs:910
  20: panic_unwind::__rust_maybe_catch_panic
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libpanic_unwind\lib.rs:80
  21: std::panicking::try
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\src\libstd\panicking.rs:271
  22: std::panic::catch_unwind
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\src\libstd\panic.rs:394
  23: test::run_test_in_process
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libtest\lib.rs:1626
  24: test::run_test::run_test_inner::{{closure}}
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95\/src\libtest\lib.rs:1504
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lovesh** [comment]
Hi @hansieodendaal. The test fails because the values (`min`, `max` and `v`) are bigger than 32 bits and the proof generation is still being passed 32 bits (argument `max_bits_in_val` in `gadget_bound_check::gen_proof_of_bounded_num`). You can change `n` in the test [here](https://github.com/lovesh/bulletproofs-r1cs-gadgets/blob/master/src/gadget_bound_check.rs#L139) to 64 and the test should work.

**Comment by lovesh** [comment]
I have added another test with the values you provide here and the proper bit size [here](https://github.com/lovesh/bulletproofs-r1cs-gadgets/blob/master/src/gadget_bound_check.rs#L151).

**Comment by hansieodendaal** [comment]
Thanks @lovesh, I have subsequently implemented a small function to count the bit size needed, will share that with you.

**Comment by hansieodendaal** [comment]
See #4

**Comment by lovesh** [comment]
Thanks. Please see my comment.
